sudo: false
language: node_js

cache:
  directories:
  - node_modules

node_js:
- '5'
- '6'
- '7'
- '8'

after_success:
  - ./node_modules/.bin/codecov

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

script: npm test

branches:
  only:
  - master
  - enzyme3
